export const ROLES = {
  SUPER_ADMIN: 'superadmin',
  ADMIN: 'admin',
  CUSTOMER: 'customer'
};

export const PERMISSIONS = {
  PLATFORM_MANAGEMENT: 'platform_management',
  MENU_WRITE: 'menu_write',
  MENU_READ: 'menu_read',
  ORDER_MANAGEMENT: 'order_management'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.PLATFORM_MANAGEMENT,
    PERMISSIONS.MENU_WRITE,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.ORDER_MANAGEMENT
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.MENU_WRITE,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.ORDER_MANAGEMENT
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.MENU_READ
  ]
};
